### ISSUE TITLE
[RFE] Provide release usable via maven dependency

### ISSUE THREAD

**Issue by svendiedrichsen** [grunka/fortuna#7]
It would be very useful to have this library provide its releases to maven central repository. Thus one could use it by maven dependency.

**Comment by grunka** [comment]
This is definitely something I've looked at a couple of times and then gotten annoyed at the process. But with this request I may just have to do something about it 🙂

**Comment by grunka** [comment]
Have a namespace set up now. Will just need to go through the steps to get it approved for proper deployment now, which is basically verifying that the pom is correct and all artifacts are acceptable.

**Comment by grunka** [comment]
It's been done. Version 2.1 is making it way out into to real world of maven currently.

**Comment by svendiedrichsen** [comment]
Thank you.
