### ISSUE TITLE
[RFE] Turn this lib into an OSGI module

### ISSUE THREAD

**Issue by svendiedrichsen** [grunka/fortuna#8]
To allow this library to be usable in an OSGI environment turn it into a module containing the proper OSGI meta data. You could use the BND maven plugin for this.

**Comment by grunka** [comment]
Sorry haven't thought about OSGi for more than half a decade at least but I did a quick thing to check it out. Did a quick test of loading and unloading it in Felix which works. Any feedback since I guess you use it 🙂

**Comment by svendiedrichsen** [comment]
I was proposing the usage of Fortuna with the Payara project as a replacement for their SecureRandom usage. I mistook their HK2 module framework for an OSGI framework. Which it can be used as AFAIK. But it isn't by the Glassfish/Payara server. Sorry for this.

But it could be useful for other circumstances where someone will use it in an OSGI only environment.

**Comment by grunka** [comment]
No worries, I'll leave the branch for now but unless someone else shows up with this need I may drop it eventually just to not add unused things.
